### ISSUE TITLE
Folder not removed on git clone failure

### ISSUE THREAD

**Issue by andham** [Hacklone/private-bower#103]
For some reason (not part of this issue) the git repo caching failed. However, during that process a folder is left in the gitRepoCache folder which makes the git commands after that fail as well.

Looking at the log below, the folder C:\Data\bower\gitRepoCache\backbone needs to be removed if the cloning fails.

> C:\Data\bower>private-bower --config ./bowerProxyConfig.json
> [bower]  20/1/15 15:13:37   Refreshing public packages...
> [bower]  20/1/15 15:13:37   Bower server started on port 5678
> [bower]  20/1/15 15:13:37   Starting git cache server
> [bower]  20/1/15 15:13:44   Loaded public packages
> [bower]  20/1/15 15:15:35   Cloning backbone ...
> [bower]  20/1/15 15:15:56   Error during cloning in C:\Data\bower\gitRepoCache\backbone
> [bower]  20/1/15 15:15:56   Command failed: Cloning into '.'...
> fatal: unable to connect to github.com:
> github.com[0: 192.30.252.131]: errno=No error
> 
> 
> [bower]  20/1/15 15:15:56   Failed to clone (maybe folder exists)git://github.com/jashkenas/backbone.git
> [bower]  20/1/15 15:15:56   undefined
> [bower]  20/1/15 15:23:37   Refreshing cached public git repositories
> [bower]  20/1/15 15:23:37   Error during "git fetch --prune --tags" in "C:\Data\bower\gitRepoCache\backbone"
> [bower]  20/1/15 15:23:37   Command failed: fatal: Not a git repository (or any of the parent directories): .git
> 
> [bower]  20/1/15 15:33:37   Refreshing cached public git repositories
> [bower]  20/1/15 15:33:37   Error during "git fetch --prune --tags" in "C:\Data\bower\gitRepoCache\backbone"
> [bower]  20/1/15 15:33:37   Command failed: fatal: Not a git repository (or any of the parent directories): .git

**Comment by andham** [comment]
This was with release 0.6.0

**Comment by andham** [comment]
Checking the code I see that a directory is created for the package before the git cloning. Why? Git clone will do this automatically AFAIK. And git will remove it as well if the cloning fails, thus resolving this issue.

**Comment by Hacklone** [comment]
Thanks for noticing, fixed it :)
