### ISSUE TITLE
CDN proxy blocked

### ISSUE THREAD

**Issue by brunobatista** [Hacklone/private-bower#104]
I work under proxy network and when start `private-bower` the CDN below have been blocked. Have any way to set another source? Thanks!

```html
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
```

**Comment by Hacklone** [comment]
You could use private repository mirroring included in the private-bower and download the bootstrap css with that but I must state that the cdn solution for css is way better than hosting your own version of it. :)

**Comment by Hacklone** [comment]
I'll close this issue as there's no response
