### ISSUE TITLE
Links in web UI return empty response in case of mirrored repositories

### ISSUE THREAD

**Issue by niksy** [Hacklone/private-bower#107]
URLs like `http://localhost:5678/jquery` accessed via web UI always return empty response. Maybe they should link to original repository?

**Comment by Hacklone** [comment]
thats not a valid url did you mean ```http://localhost:5678/packages/jquery```?

**Comment by niksy** [comment]
When you open `http://localhost:5678/` in browser and click on package link you are redirected to page without `/packages/` path part.

**Comment by Hacklone** [comment]
please check your bowerRepository.json, maybe you've accidentally registered jQuery over the public registry :)

**Comment by niksy** [comment]
Hmm, maybe I am doing something wrong :)

So, my `.bowerrc` points to my private server and then I initiate install via `bower install jquery --save` which clones jQuery repo if it’s not already cloned.

After that, my `.bowerRepository.json` looks like this:

```json
{
    "jquery": {
        "name": "jquery",
        "repo": "git://localhost:6789/jquery",
        "hits": 1,
        "cachedRepo": "git://localhost:6789/jquery"
    }
}
```

**Comment by Hacklone** [comment]
Oh then it's by design, though we could create a middleware in the server to serve some html showing the package name and location.

**Comment by Hacklone** [comment]
This is no longer an issue as the webUI now shows the package details instead of jumping to the source.
