### ISSUE TITLE
bower install <Package Name> with .bowercc file configured to http://localhost:5678 gives 406 error

### ISSUE THREAD

**Issue by aamolgote** [Hacklone/private-bower#108]
I have set up private bower repository, I have published package to it using http://localhost:5678/registerpackage end point, package gets registered but when I try to consume it or install it using bower command
bower install "Package Name" it gives error bower EINVRES Request to http://localhost:5678/packages/"Package Name" failed with 406
.

I tried to log the Response object and it looks like some thing below
{"statusCode":406,"body":"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//
EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"htt
p://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" cont
ent=\"text/html; charset=iso-8859-1\"/>\r\n<title>406 - Client browser does not
accept the MIME type of the requested page.</title>\r\n<style type=\"text/css\">
\r\n\r\n</style>\r\n</head>\r\n<body>\r\n<d
iv id=\"header\"><h1>Server Error</h1></div>\r\n<div id=\"content\">\r\n <div cl
ass=\"content-container\"><fieldset>\r\n  <h2>406 - Client browser does not acce
pt the MIME type of the requested page.</h2>\r\n  <h3>The page you are looking f
or cannot be opened by your browser because it has a file name extension that yo
ur browser does not accept.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n<
/html>\r\n","headers":{"cache-control":"private","content-type":"text/html","ser
ver":"Microsoft-IIS/7.5","x-powered-by":"ASP.NET","date":"Tue, 27 Jan 2015 14:16
:07 GMT","content-length":"1346","connection":"Keep-Alive","set-cookie":["Bear=q
g1Gu4wg1m+cfcHL76wfsmgOh+wkLo35tpsHPFre7w8=; domain=.239.110; path=/"]},"request
":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"165.37.239.110",
"port":80,"hostname":"165.37.239.110","hash":null,"search":null,"query":null,"pa
thname":"/","path":"/","href":"http://165.37.239.110/"},"method":"GET","headers"
:{"User-Agent":"curl/7.21.4 (universal-apple-darwin11.0) libcurl/7.21.4 OpenSSL/
0.9.8r zlib/1.2.5","accept":"application/json"}}}

**Comment by Hacklone** [comment]
Hey,
Something funky is going on with the request it seems like an other server (IIS) is responding ```ver":"Microsoft-IIS/7.5","x-powered-by":"ASP.NET``` Did you set the .bowerrc to the correct url and port?

**Comment by aamolgote** [comment]
This is how my .bowerrc fil looks like
{
  
 "analytics": false,
  
 "directory": "source/vendor",

 "interactive": false,

 "json": "bower.json",
 "registry": {
    "search": [
      "http://localhost:5678"
    ],
	"register": "http://localhost:5678",
	"publish": "http://localhost:5678"
  },
  "proxy":"http://proxy.corp.com:8083/",
  "https-proxy":"http://proxy.corp.com:8083/"

}

Also I had stopped IIS Service then I started getting this response
{"statusCode":503,"body":"<HTML><HEAD>\r\n<meta http-equiv=\"Pragma\" content=\"
no-cache\">\r\n<TITLE>Network Error</TITLE>\r\n</HEAD>\r\n<BODY>\r\n<img src=htt
p://www.bankofamerica.com/global/mvc_objects/images/mhd_reg_logo.gif>\r\n<FONT f
ace=\"Helvetica\">\r\n<big><strong></strong></big><BR>\r\n</FONT>\r\n<blockquote
>\r\n<TABLE border=0 cellPadding=1 width=\"80%\">\r\n<TR><TD>\r\n<FONT face=\"He
lvetica\">\r\n<big>Network Error (tcp_error)</big>\r\n<BR>\r\n<BR>\r\n</FONT>\r\
n</TD></TR>\r\n<TR><TD>\r\n<FONT face=\"Helvetica\">\r\nA communication error oc
curred: Connection refused\r\n</FONT>\r\n</TD></TR>\r\n<TR><TD>\r\n<FONT face=\"
Helvetica\">\r\nThe Web Server may be down, too busy, or experiencing other prob
lems preventing it from responding to requests. You may wish to try again at a l
ater time.\r\n</FONT>\r\n</TD></TR>\r\n<TR><TD>\r\n<FONT face=\"Helvetica\" SIZE
=\"2\">\r\n<BR>\r\n\r\n</FONT>\r\n</TD></TR>\r\n</TABLE>\r\n</blockquote>\r\nbcp
xyrch5\r\n</BODY></HTML>\r\n","headers":{"cache-control":"no-cache","pragma":"no
-cache","content-type":"text/html; charset=utf-8","proxy-connection":"Keep-Alive
","connection":"Keep-Alive","content-length":"868"},"request":{"uri":{"protocol"
:"http:","slashes":true,"auth":null,"host":"165.37.239.110","port":80,"hostname"
:"165.37.239.110","hash":null,"search":null,"query":null,"pathname":"/","path":"
/","href":"http://165.37.239.110/"},"method":"GET","headers":{"User-Agent":"node
/v0.10.35 win32 ia32","accept":"application/json"}}}

Also Instead of local host I tried with IP as well no luck.

AIso I hit below Url  in browser
http://localhost:5678/packages/BowerPOC

It Returns valid JSON 
{
  "name": "BowerPOC",
  "url": "git://github.com/aamolgote/BowerPOC.git",
  "hits": 1
}

**Comment by Hacklone** [comment]
Hey try replacing the registry property in the .bowerrc file to "registry": "http://localhost:5678".
Hope this helps

**Comment by Hacklone** [comment]
Did that help? Can I close this issue?

**Comment by aamolgote** [comment]
Yes please.


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Barna Tóth <notifications@github.com> </div><div>Date:02/12/2015  1:46 PM  (GMT-05:00) </div><div>To: Hacklone/private-bower <private-bower@noreply.github.com> </div><div>Cc: aamolgote <aamolgote@hotmail.com> </div><div>Subject: Re: [private-bower] bower install <Package Name> with .bowercc file configured to http://localhost:5678 gives 406 error (#108) </div><div>
</div>
Did that help? Can I close this issue?

---
