### ISSUE TITLE
Please add detailed info from bower.json for each package to the UI

### ISSUE THREAD

**Issue by isbad** [Hacklone/private-bower#109]
It would be nice if you can add some bower.json's options for each package to the UI. I mean version, main, keywords and dependencies. 
Somehow in the package list (expandable section) or on the single page like so https://www.npmjs.com/package/private-bower

Thanks

**Comment by zetorama** [comment]
+1. [Dependents list](https://www.npmjs.com/browse/depended/body-parser) would be really great.

**Comment by brunowego** [comment]
+1

**Comment by jsancho** [comment]
+1

**Comment by jsancho** [comment]
+1
