### ISSUE TITLE
Whitelisting of public packages

### ISSUE THREAD

**Issue by hutdev** [Hacklone/private-bower#115]
In a corporate environment administrators may want to restrict access to public packages by providing a whitelist of packages that developers may use.

I propose a feature by which server administrators can configure such a whitelist and all packages retrieved from the public registry will be filtered against said whitelist. I suggest the whitelist to be configured as a property in the server's config JSON, e. g.:

"publicPackagesWhitelist" : ["angular"]

The filter will be applied to bower search as well as bower install of course.
If the property is omitted in the config JSON, all packages from the public registry will be provided.

**Comment by Hacklone** [comment]
Hey,
This is a great idea, will put this on v1.0
Thanks :+1:
