### ISSUE TITLE
Manually refresh repository cache?

### ISSUE THREAD

**Issue by topherfangio** [Hacklone/private-bower#117]
Hi there,

We're using private-bower behind a corporate firewall and it's working pretty great. We're also developing our own internal bower components, though, and have an automatic build process which releases a development version of those components.

Is there any way to manually fire off the git repo cache refresh? Ideally, this we would be able to curl a URL on the private-bower server and wait for a response or something, but even knowing a manual command that we could type/script would be great.

Thanks!

**Comment by Hacklone** [comment]
Hey,
This is a great idea, I'll do it in version 1.0. Until then you'll only need to write a script that does this:
- go through all the folders in the private-bower repo cache folder
- and call this in them: ```git pull```

**Comment by Hacklone** [comment]
Added the /refresh url option, will be available with 1.0.0
