### ISSUE TITLE
installing from gitlab repo

### ISSUE THREAD

**Issue by divramod** [Hacklone/private-bower#119]
I try to install a bower repo i registered to my local private bower instance.
The git host is a private gitlab instance.

 bower install bower-test is given me the error

    bower bower-test#*          not-cached git://github.com/EvandroLG/bower-test.git#*
    bower bower-test#*             resolve git://github.com/EvandroLG/bower-test.git#*
    bower bower-test#*             ECMDERR Failed to execute "git ls-remote --tags --heads     git://github.com/EvandroLG/bower-test.git", exit code of #128

    Additional error details:
         fatal: remote error: 
         Repository not found.

I know that private-bower is running correctly because i registered a github.com repository which i can install.

my .bowerrc

    {
      "registry" : {
        "register" : "http://localhost:5678"
      },
    "search": [
          "http://localhost:5678"
       ]
    }

i can run
    bower install http://myprivategitlabip/bower/bower-test.git
with success.

But i like to run bower install bower-test.

any suggestions?

**Comment by johnrc** [comment]
It looks like you've registered `bower-test` with a `github.com` url not a private gitlab url. Remove bower-test with `curl --data "name=bower-test" http://127.0.0.1:5678/removePackage` and re-register with `bower register http://myprivategitlabip/bower/bower-test.git`. Then to test, run `bower cache clean` and `bower install bower-test`.

**Comment by Hacklone** [comment]
Thanks @johnrc :+1: 
Did this help @divramod ?

**Comment by Hacklone** [comment]
I'll close this issue.
