### ISSUE TITLE
Authentication Document

### ISSUE THREAD

**Issue by thalesfsp** [Hacklone/private-bower#121]
Hi!

 Do you have more documentation about documentation? I don't want anyone registering packages, only those with the password.

Cheers!

**Comment by hvdb** [comment]
Hello,

If you enable authentication, and set a password, nobody can register a package without having the password

Don't know what kind of documentation you mean?

See authentication part:
Example:
```javascript
{
    "port": 5678,
    "registryFile": "./bowerRepository.json",
    "timeout": 144000,
    "disablePublic": false,
    "publicRegistry": "http://bower.herokuapp.com/packages/",
    "authentication": {
        "enabled": true,
        "key": "password"
    },
    "repositoryCache": {
        "cachePrivate": false,
        "git": {
            "enabled": false,
            "cacheDirectory": "./gitRepoCache",
            "host": "localhost",
            "port": 6789,
            "publicAccessURL" : null,
            "refreshTimeout": 10
        },
        "svn": {
            "enabled": false,
            "cacheDirectory": "./svnRepoCache",
            "host": "localhost",
            "port": 7891,
            "publicAccessURL" : null,
            "refreshTimeout": 10
        }
    },
    "proxySettings" : {
        "enabled": false,
        "host": "proxy",
        "username": "name",
        "password" : "pass",
        "port": 8080,
        "tunnel": false
    },
    "log4js" : {
        "enabled": false,
        "configPath" : "log4js.conf.json"
    }
}
```

**Comment by Hacklone** [comment]
Thanks @hvdb :)
Did this help @thalesfsp ?

**Comment by thalesfsp** [comment]
@Hacklone I forked your version and working now to develop/augment the security system, more properly for enterprise use. Thank you ;)

**Comment by Hacklone** [comment]
Hey,

Sounds good :)
Could you please use the updated version in the 1.0.0 branch (5ec09502d4711b625f1db28a63a1a0a187841103)
A lot changed in there :)

Thanks

**Comment by Hacklone** [comment]
I'll close this issue for now.

**Comment by thalesfsp** [comment]
Thanks ;)

**Comment by Hacklone** [comment]
I'll fix that :+1: 
Please use that branch anyway :)

**Comment by Hacklone** [comment]
Nothing to fix, it only shows the state of the master branch's build :)
