### ISSUE TITLE
Git using HTTPS

### ISSUE THREAD

**Issue by pantocrator27** [Hacklone/private-bower#123]
I apologize if this is the wrong forum for this question.  Is it possible to specify https:// vs git:// in the configuration file?  This is especially useful when behind a corporate proxy and you need to specify https to go through it.

**Comment by johnrc** [comment]
This is similar to the fix in #111 and #102 You can do this by running `git config --global url."https://".insteadOf git://` on the server (or wherever you're running private-bower). This adds the following to your `~/.gitconfig`:

    [url "https://"]
        insteadOf = git://

**Comment by Hacklone** [comment]
Thanks @johnrc. :)
Did this solve your problem @pantocrator27?

**Comment by pantocrator27** [comment]
This did.  Thank you guys ever so much!!!
