### ISSUE TITLE
bower EINVERS Request to http://localhost:5678/packages/angular failed with 500

### ISSUE THREAD

**Issue by vert3x** [Hacklone/private-bower#128]
Hi,

I always get this error "bower **EINVERS** Request to http://localhost:5678/packages/angular failed with 500" whenever I use bower install ! Here's my .bowerrc file :
```
{
	"directory": "components",
    "registry": "http://localhost:5678",
    "timeout": 300000
}
```

I'm behind a proxy, the proxy settings I added to the bower.conf.json are :
```
"proxySettings" : {
        "enabled": true,
        "host": "my_proxy_addr",
        "port": port,
        "tunnel": false
    },
```

When I use this url "http://localhost:5678/packages/angular" directly in the browser I get the dependency informations : 
```
{
  "name": "angular",
  "url": "git://github.com/angular/bower-angular.git",
  "hits": 8422523
}
```

Everything works fine If I don't use the private-bower, it's seems like the private-bower won't fallback to the public repository!

**Comment by Hacklone** [comment]
Hey,

The fallback is working because in the browser you got the desired output. 
Basically the bower client does the same as your browser :)

Did your private-bower server log some error, maybe the bower client calls the private-bower server differently...

Barna

**Comment by vert3x** [comment]
Sorry, but I haven't activated the logging for private-bower, when I activate it I get an error says "Exception message:Error: ENOENT, no such file or directory 'log4js.conf.json'".

Anyways, I think the problem was related to my company proxy, because at home everything works fine when I disable proxy settings for private-bower :/

**Comment by Hacklone** [comment]
It seems like private-bower cannot find the log4js file, did you acciedntaly delete it? If not place it next to the bower.conf.json file and it should work :)

**Comment by vert3x** [comment]
no I haven't delete it and it is placed next to bower.con.json.

![screen shot 2015-04-18 at 12 27 39 pm](https://cloud.githubusercontent.com/assets/3410430/7215238/56165722-e5c6-11e4-9119-1e6afd7a23b7.png)

**Comment by Hacklone** [comment]
How are you running the server? Maybe there's something wrong with that..

**Comment by vert3x** [comment]
With the command "private-bower".
I even re-installed Bower and Private-Bower, but I have the same problem, again just at work, at home everything works perfect.

**Comment by vert3x** [comment]
Another thing, sometimes I get this in the console after running the private-bower :
```
[bower]  20/4/15 08:11:16   Refreshing public packages...
[bower]  20/4/15 08:11:16   Cached public packages loaded
[bower]  20/4/15 08:11:16   Bower server started on port 5678
something went wrong on the request { host: 'bower.herokuapp.com',
  port: null,
  path: '/packages/',
  method: 'GET' }
```

**Comment by vert3x** [comment]
Ok, I figure out that the error 
```
something went wrong on the request { host: 'bower.herokuapp.com',
  port: null,
  path: '/packages/',
  method: 'GET' }
```
came only when I disable proxy setting in the bower.conf.json
but still have the same error anyway :/

Could you please help me out at least on how to get some logging with bower or private-bower?

**Comment by vert3x** [comment]
Ok I tried to have some loggin, the problem I told you about the log4j "Exception message:Error: ENOENT, no such file or directory 'log4js.conf.json'" I fixed it by using the absolute url for configPath

```
"log4js" : {
        "enabled": true,
        "configPath" : "D:\\...\\log4js.conf.json"
    }
```
Logging works fine now, but again, no luck, I haven't any problem, I just saw "Loaded public packages" ... "Public registry cached"

And we're back to "bower EINVERS ... " even if I try "bower install non_existant_package" I get that same error -_-

**Comment by Hacklone** [comment]
Hey,

Did you try setting this on the client side: ```git config --global url."https://".insteadOf git://```?
It should help in case of using a proxy.

**Comment by vert3x** [comment]
Yes I did that.

**Comment by Hacklone** [comment]
Okay it seems like your private-bower works fine the problem will be with the client. You set the .bowerrc registry to localhost, so your trying to install a package on the same machiene as your private-bower runs on.
Is it possible that you've set proxy settings for the bower client too? If yes then through the proxy you won't be able to access localhost.

**Comment by vert3x** [comment]
Yes I set proxy settings in .bowerrc too, but even if I delete them I still have the same error.
That's so weird, everything is working fine at home.

**Comment by johnrc** [comment]
You might also try running `bower cache clean` just to make sure you're starting fresh.

**Comment by vert3x** [comment]
I tried that.
Another thing, even if I don't start the private-bower server, I get the same error o_O

**Comment by Hacklone** [comment]
Yes, because you bower client can't even reach your private-bower.
Your bower client's requests go through the proxy and from the proxy your private-bower server is not reachable. 
Search for every .bowerrc file on your machine and remove your proxy settings from every one of them because .bower works like .git it goes up the folder tree and if it finds one than it'll try to use the proxy.
If that doesn't help try it from a totally other machine.
If that doesn't help either start a wire shark and find for the call from your bower client and nslookup the ip it goes to.

**Comment by altukhov-a** [comment]
Maybe you use environment variables HTTP_PROXY and HTTPS_PROXY. This variables use bower. Check run "bower search jquery" in folder without .bowerrc. If you behind proxy you must received error, that means bower not use proxy, if not check environment variables and user folder exists .bowerrc with proxy settings and remove them. Now add .bowerrc with 
{
  "registry": "http://localhost:5678",
  "timeout": 300000
}
in the same folder and try run "bower search jquery" again.

**Comment by Hacklone** [comment]
Did you manage to solve this issue with your proxy?

**Comment by Rorkal** [comment]
Hello guys ! 

I got the exact same error behind a proxy: 
"*bower EINVERS Request to http://localhost:5678/packages/angular failed with 500*".

 Here is my config:

private-bower.config.json :
```json
{
    "port": 5678,
    "registryFile": "./bowerRepository.json",
    "timeout": 144000,
    "public": {
        "disabled": false,
        "registry": "http://bower.herokuapp.com/packages/",
        "registryFile": "./bowerRepositoryPublic.json",
        "whitelist": [],
        "blacklist": []
    },
    "authentication": {
        "enabled": false,
        "key": "password"
    },
    "repositoryCache": {
        "cachePrivate": true,
        "git": {
            "enabled": true,
            "cacheDirectory": "./gitRepoCache",
            "host": "localhost",
            "port": 6789,
            "publicAccessURL" : null,
            "refreshTimeout": 10
        },
        "svn": {
            "enabled": true,
            "cacheDirectory": "./svnRepoCache",
            "host": "localhost",
            "port": 7891,
            "publicAccessURL" : null,
            "refreshTimeout": 10
        }
    },
    "proxySettings" : {
        "enabled": true,
        "host": "xxx.xxx.xxx.xxx",
        "port": 8080,
        "tunnel": false
    },
    "log4js" : {
        "enabled": true,
        "configPath" : "log4js.conf.json"
    }
}
```
log4js.conf.json :
```json
{
"appenders": [
{
"type": "dateFile",
"filename": "private-bower.log",
"pattern": "-yyyy-MM-dd",
"alwaysIncludePattern": false
},
{
"type": "console"
}
],
"replaceConsole": true
}
```
.bowerrc :
```json
{
    "directory": "src/vendor",
    "registry": "http://localhost:5678" 
}
```
@altukhov-a's answer solved the problem, i had http_proxy and https_proxy set, removing them solved the problem.

(Thanks!)
