### ISSUE TITLE
1.0.2 - Private packages are not re-loaded on restart

### ISSUE THREAD

**Issue by kodypeterson** [Hacklone/private-bower#131]
Private packages are not being reloaded into memory from file when process is restarted.

**Comment by gigaga** [comment]
+1 :(

**Comment by Hacklone** [comment]
This should be fixed in 1.0.3
Could you try it out?

**Comment by gigaga** [comment]
Tests done with 1.0.3 but same issue :(

**Comment by gigaga** [comment]
Ok, it is needed to delete the old bowerRespository.json which contains [] and after that, it is ok :)
Thx a lot!

**Comment by Hacklone** [comment]
1.0.4 should fix the issue, does it work for you now with the old bowerRepositry?

**Comment by kodypeterson** [comment]
@Hacklone - Looks better but number of hits are missing now

**Comment by nomve** [comment]
I could send a PR, but it's because of probably a typo on one line inside privatePackageStore.js .
