### ISSUE TITLE
 Cache public git repositories: package registered after git clone failed!!

### ISSUE THREAD

**Issue by ypupo2002** [Hacklone/private-bower#134]
hi,

After a failed attempt to cache a package and it's public repository, the clone operation fails due to crappy internet connection, but the package get registered anyways:

This is the log for private-bower:

```
[bower]  22/4/15 16:07:27   Error during cloning in fontawesome
[bower]  22/4/15 16:07:27   Command failed: Cloning into 'fontawesome'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

[bower]  22/4/15 16:07:27   Registered package: fontawesome
```

And after this, any attempt to install the package on a cliente gives:

```
pupo@private-bower:~/test-bower$ bower install fontawesome
bower fontawesome#*         not-cached git://private-bower.localdomain/fontawesome#*
bower fontawesome#*            resolve git://private-bower.localdomain/fontawesome#*
bower fontawesome#*            ECMDERR Failed to execute "git ls-remote --tags --heads git://private-bower.localdomain/fontawesome", exit code of #128 fatal: repository 'git://private-bower.localdomain/fontawesome' not found

Additional error details:
fatal: repository 'git://private-bower.localdomain/fontawesome' not found
```

**Comment by Hacklone** [comment]
Hey,

Simply delete the fontawesome folder from the gitRepoCache folder.
Remove the frontawsome package ```DELETE call to /packages/fontawesome```

And then try install again

**Comment by ypupo2002** [comment]
OK, 
That worked like a charm, but my question is: why the package get registered even when the clone operation has failed? this is the expected behavior?

**Comment by Hacklone** [comment]
Hey,

Yes that is because the clone can fail, but basically the next git pull on that repo can still succeed :)
Can we close this issue?

**Comment by ypupo2002** [comment]
In this case, no future pull operation can succeed, because the git repository folder wasn't created due to the nature of the error, maybe you can verify if the clone operation was entirely rolled back (i.e. the repo folder doesn't exist on the cache).
