### ISSUE TITLE
einvformat Invalid URL format error

### ISSUE THREAD

**Issue by wsrast** [Hacklone/private-bower#138]
I'm trying to register a simple test repo to private-bower using a localhost git server (which I've verified is running fine for repo creation, cloning, etc.), and failing with every combination of commands that I try due to a very unhelpful error message. I can find no information other than people running into the same error if they try to use upper-case package names, which I am not. Here's the dump:

C:\dev\gitblit-test>bower register testrepo git://localhost/testrepo.git
bower testrepo#*               resolve git://localhost/testrepo.git#*
bower testrepo#*              checkout master
bower testrepo#*          invalid-meta testrepo is missing "main" entry in bower.json
bower testrepo#*          invalid-meta testrepo is missing "ignore" entry in bower.json
bower testrepo#*              resolved git://localhost/testrepo.git#ffc2f7be52
? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue?: Yes
bower testrepo                register git://localhost/testrepo.git
**bower                       EINVFORMAT Invalid URL format**

I'm nearly tearing my hair out over here. Anyone have any insights?

.bowerrc file:
{
	"registry": "http://localhost:5678",
	"timeout": 300000
}

bower.json:
{
  "name": "testrepo",
  "version": "0.0.1",
  "description": "testing pre-created repo",
  "main": "index.html",
  "authors": [
    "foo@foo.com"
  ],
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "./bower_components",
    "test",
    "tests"
  ]
}

**Comment by wsrast** [comment]
I'm going to answer my own question here in case anyone ever runs into this and ends up here off a google search.

The problem was in my own misunderstanding about how bower works. Bower needs a fully populated git repo to point to before it can register it, even when using a local, private bower registry. Particularly, it has to have that bower.json in place.

I was getting errors because I'd created the git repo on my localhost server, cloned it to a folder, then added the bower.json and other files in place. I attempted to register the "testrepo" package prior to committing the files to the git repo, wrongly thinking that bower would help take care of that step.

I realize this question would be better off somewhere like stackoverflow, so admin, if you want to wipe this one, go for it, but I may not be the only one coming here looking for more info. So, in the interests of helping others out, here's the steps i went through to fix it:

git add .
git commit
git push
bower register testrepo git://localhost/testrepo.git

**Comment by Hacklone** [comment]
If you have the time, you could make a wiki page about this.

Thanks :)
