### ISSUE TITLE
Local git server: stuck on checkout master

### ISSUE THREAD

**Issue by elgerm** [Hacklone/private-bower#140]
Registring packages with github as git repository works, but when using our local bonobo git server bower gets stuck on 'checkout master'.

```
bower test1#*  resolve http://servername/Bonobo.Git.Server/test1.git
bower test1#*  checkout master
... wait forever
```

The git server and repository are accessable though and there is no error in the logs. We're using private-bower and bonobo on a windows 2008 server.

Any ideas?

**Comment by johnrc** [comment]
Try running `git clone http://servername/Bonobo.Git.Server/test1.git`. Was it successful?

Are the git repositories public or private? If private, you may need to have ssh keys setup or a cached password so it'll authenticate and automatically pull down.

**Comment by elgerm** [comment]
Should have mentioned it, but every git command to that server works in the
same shell. Only when bower tries it for me it hangs. It's a pubic repo.

**Comment by mxurshid** [comment]
Same problem. When I tried with <code>git clone</code> , it was successful

**Comment by joeljeske** [comment]
I am getting the same behavior. It seems like bower v1.4.x hangs but with v1.3.12 it works. Can anyone confirm?

**Comment by joeljeske** [comment]
I happened to be using bonobo git server as well. I think it is [an issue][0] in bonobo git server that failed when requested to do a shallow clone. Shallow cloning [was added to http git servers in bower 1.4][1]. I do not think it is an issue with this bower registry. 

[0]: https://github.com/jakubgarfield/Bonobo-Git-Server/issues/166#issuecomment-106911042
[1]: https://github.com/bower/bower/pull/1628

**Comment by mxurshid** [comment]
@joeljeske you are right! It is an issue in bonobo git server. <a href='https://github.com/jakubgarfield/Bonobo-Git-Server/pull/248'>This issue fixed</a> and merged, but not released yet. I cloned bonobo git server's repo, and built, then published to IIS. 
Now it works with the latest bower and private-bower.

**Comment by Hacklone** [comment]
Can we close this issue? As it seems to be solved :)

**Comment by mxurshid** [comment]
+1
