### ISSUE TITLE
bower EPERM unlink

### ISSUE THREAD

**Issue by altukhov-a** [Hacklone/private-bower#142]
When I install new package I get this error
![bower_error](https://cloud.githubusercontent.com/assets/2371820/8034380/b31e7ce6-0def-11e5-997d-926737b9c692.png)

My private bower config:

{
    "port": 5678,
    "registryFile": "./bowerRepository.json",
    "timeout": 144000,
    "public": {
        "disabled": false,
        "registry": "http://bower.herokuapp.com/packages/",
        "registryFile": "./bowerRepositoryPublic.json",
        "whitelist": [],
        "blacklist": []
    },
    "authentication": {
        "enabled": false,
        "key": "password"
    },
    "repositoryCache": {
        "cachePrivate": false,
        "git": {
            "enabled": false,
            "cacheDirectory": "./gitRepoCache",
            "host": "localhost",
            "port": 6789,
            "publicAccessURL": null,
            "refreshTimeout": 10,
            "parameters": {
                "timeout": 60000,
                "max-connections": 100
            }
        },
        "svn": {
            "enabled": false,
            "cacheDirectory": "./svnRepoCache",
            "host": "localhost",
            "port": 7891,
            "publicAccessURL": null,
            "refreshTimeout": 10
        }
    },
    "proxySettings" : {
        "enabled": true,
        "host": "10.18.32.1",
        "port": 3128,
        "tunnel": false
    },
    "log4js" : {
        "enabled": false,
        "configPath" : "log4js.conf.json"
    }
}

In folder where I run "bower install svg-pan-zoom" config .bowerrc:
{
  "registry": "http://localhost:5678",
  "timeout": 300000
}
I get error

Then I change settings to
{
  "registry": "http://bower.herokuapp.com",
  "proxy":"http://10.18.32.1:3128",
  "https-proxy":"http://10.18.32.1:3128"
}
it works fine
Can you help me?

**Comment by johnrc** [comment]
Since you're behind a proxy, you either have to enable `repositoryCache` or else set the proxy like you have. Does it work to set the registry to private bower but keep the proxy settings?

**Comment by altukhov-a** [comment]
Yes, when I change config .bowerrc to
{
  "registry": "http://localhost:5678",
  "proxy":"http://10.18.32.1:3128",
  "https-proxy":"http://10.18.32.1:3128"
}
It's work, 
but when I set

**Comment by Hacklone** [comment]
Hey,

This is an issue with your bower client and not with private-bower as the client got the github url.
Probably the console didn't have permission to delete (unlink) that appdata file.
Try running it in Administration mode.
I'm closing this issue as it's not connected to private-bower.
