### ISSUE TITLE
How to provide serverConfig.json when running as a Windows Service?

### ISSUE THREAD

**Issue by jsancho** [Hacklone/private-bower#143]
Hi,

I have managed to setup the Windows service with the wiki instructions.

However, I have not seen how can I provide the --config c:\path-to-config\serverConfig.json value to the daemon created by qckwinsvc.

I have tried modifying the xml config for the exe itself, but it feels like node-windows would allow for this (or maybe I need some extra escaping sequence)

How would you suggest to address this? 
Would it make sense for private-bower to override its defaults if a serverConfig.json is found in the local path? Just like it parses any existing bowerRepository.json, bowerRepositoryPublic.json files?

thanks,

Jaume

**Comment by johnrc** [comment]
Have you tried adding it as part of the `Node script path`? So something like `C:\path\to\private-bower --config C:\path\to\serverConfig.json`.

**Comment by jsancho** [comment]
@johnrc that works just fine when I'm running manually.
However, my doubt is in how to supply those parameters when running private-bower wrapped as a service. 
With qckwinsvc, as it's explained in the wiki https://github.com/Hacklone/private-bower/wiki/Install%20as%20a%20Windows%20service

**Comment by johnrc** [comment]
Have you tried passing the `--config /path/to/config` when providing the private-bower script path?

**Comment by jsancho** [comment]
@johnrc yes, of course. 
I've tried feeding those parameters via the privatebowerserver.xml generated by qckwinsvc.
That's including several escape sequences and quoting, but it hasn't worked.

Is this something that you have done before? do you know if the passing a custom config us actually supported when using a Windows service?

I suppose that the least path of resistance would be to have private-bower read a serverConfig.json from the root path (if available). Just like it happens with bowerRepository.json and bowerRepositoryPublic.json 
If I find the time I could even create a PR for this, but it would be nice to know whether I'm looking at an actual issue or if I'm simply not configuring this properly.

**Comment by Hacklone** [comment]
Hey,

I think you can't add parameters to a win service, though private-bower should read the config from the default location: bower.conf.json if it doesn't read that then it's a bug.
I'm on holiday so I'll only be able to check this next week.
Try modifying the default bower.conf.json file so you could recognize if it uses that config.

Thanks,
Barna

**Comment by Hacklone** [comment]
You can pass in parameters when qckwinsvc asks  for the script to run (--config path/to/your/config)

**Comment by jsancho** [comment]
@Hacklone that's what it was, I didn't realise that bower.conf.json was the default settings for the server.
Maybe it would make sense to add a paragraph to the documentation, so that other daft guys like myself pick up on this?
Same would apply to the bowerRepository.json and bowerRepositoryPublic.json.
Anyway, thanks for such great work
