### ISSUE TITLE
repositoryCache when public disabled

### ISSUE THREAD

**Issue by omrilitov** [Hacklone/private-bower#144]
Hi,
I want to use private-bower on a closed network, so I use the repositoryCache feature to serve repositories I pulled manually and then put them on the cache.
However, I'm forced to set public as true so the cache would work which causes errors because I'm on a closed network.
Is there a way to use the cache without using the public?
Thanks!

**Comment by johnrc** [comment]
I don't think there's a built-in way right now. You could always host the git server separate from private-bower and then register the packages with that git url. I realize that's a bit of a hassle though.

**Comment by omrilitov** [comment]
Can I make a pull request to separate them?
So I'll be able to use cache without public

**Comment by johnrc** [comment]
It sounds good to me. I'm not the maintainer but assume @Hacklone will take a pull request.
