### ISSUE TITLE
 401 - Unauthorized

### ISSUE THREAD

**Issue by aRTURIUSS** [Hacklone/private-bower#145]
Hi, Please help me, i've installed private-bower module and set authentification to "true". When i'm trying to register package i have the following error: bower  EUNKNOWN Unknown error: 401 - Unauthorized

Full stacktrace:
bower register js-git git@*.*.*.*:root/js-git.git
bower js-git#*                 resolve git@*.*.*.*:root/js-git.git#*
bower js-git#*                checkout 0.7.7
bower js-git#*            invalid-meta js-git is missing "main" entry in bower.json
bower js-git#*            invalid-meta js-git is missing "ignore" entry in bower.json
bower js-git#*                resolved git@*.*.*.*:root/js-git.git#0.7.7
? Registering a package will make it installable via the registry (http://my_private_bower:5678), continue? Yes
bower js-git                  register git@*.*.*.*:root/js-git.git
bower                         EUNKNOWN Unknown error: 401 - Unauthorized

When i'm setting authentification in "false" in bower.conf.json everything is ok and i see the package in package list.

**Comment by Hacklone** [comment]
Hey,

If you turn on authentication you'll only be able to register packages by calling the API as described in the README.md The bower client doesn't support authentication.

Please close this issue if you've managed to register a package through the API as described.

Hope I managed to help.

Barna

**Comment by aRTURIUSS** [comment]
Thank you!

**Comment by diegozhu** [comment]
```
{
   "directory": "bower_components",
    "registry": {
        "search": ["http://192.168.99.100:10010/repository/bower-group"],
        "register": "http://admin:admin123@192.168.99.100:10010/repository/bower-hosted/"
    },
    "resolvers": ["bower-nexus3-resolver"],
    "nexus": {
        "username": "admin",
        "password": "admin123"
    }
}
```
from:
[https://issues.sonatype.org/browse/NEXUS-10165](https://issues.sonatype.org/browse/NEXUS-10165)
