### ISSUE TITLE
Private bower has an issue while refresh private git repository

### ISSUE THREAD

**Issue by AlbanAndrieu** [Hacklone/private-bower#146]
Hi,

private-bower is trying to do the following:

```
cd /files/bower/private-bower/gitRepoCache/nabla-auth
git fetch --prune --tags
```

nabla-auth is a private repo from hosted on Stash
I am using private-bower 0.6.5

This is working using the same user by hand,
but private-bower failed

#for each repo, I found that the following is working
```
git config --local --list
git config http.sslVerify false
```

Even though global already has http.sslverify=false
```
git config --global --list
http.sslverify=false
user.email=mgr.jenkins@misys.com
user.name=MGR Jenkins
```

Best regards,

Alban

**Comment by Hacklone** [comment]
Hey,

Could you send the error details when the server tries to run ```git fetch --prune --tags```?
If you're using https then you should install your self signed cert on the private-bower server ```git config http.sslCAInfo /etc/ssl/certs/my_root_cert.pem```

Thanks,
Barna

**Comment by AlbanAndrieu** [comment]
Indeed we are using ssl but without properly managing certificates.
As my company does not provide valid certificate you can close this issue.
Workaround git config http.sslVerify false is OK for us
