### ISSUE TITLE
private-bower/site/index.html's ng-repeat references undefined property "repos"

### ISSUE THREAD

**Issue by gregswindle** [Hacklone/private-bower#148]
## Are registered private-bower private packages supposed to have a `repo` property?

The [private-bower/site/index.html](https://github.com/Hacklone/private-bower/blob/master/site/index.html#L77)'s `ng-repeat` references a `package.repo`, which does not appear to be part of the `private-bower/lib/service/packageStores/privatePackageStore.js` API:

```html
<div ng-repeat="package in mainController.packages | filter:{ name: packageFilter }" class="package container-fluid">
    <div class="row">
        <div class="col-md-6 col-xs-6">
            <a href="{{ package.repo.replace('git:', 'http:') }}" target="_blank">
                <h3 style="line-height: 1.5em">
                    {{ package.name }}
                </h3>
            </a>
        </div>
``` 
When I register a bower-package, the following JSON interface appears in the `private-bower/bowerRespository.json` (note there is not a `repo` property):

```json
[
  {
    "name": "my-cool-bower-component",
    "url": "http://repos.example.com/my-cool-bower-component.git",
    "hits": 4
  }
]
```
For now, I have simply modified the `private-bower/site/index.html`'s `ng-repeat` to use the `url` property instead:
```html
<div ng-repeat="package in mainController.packages | filter:{ name: packageFilter }" class="package container-fluid">
    <div class="row">
        <div class="col-md-6 col-xs-6">
            <!-- <a href="{{ package.repo.replace('git:', 'http:') }}" target="_blank"> -->
            <a href="{{ package.url.replace('git:', 'http:') }}" target="_blank">
                <h3 style="line-height: 1.5em">
                    {{ package.name }}
                </h3>
            </a>
        </div>
``` 
This works, but it would be nice to distinguish the package `url` from its `repos`. Is this a defect?

**Comment by Hacklone** [comment]
Hey,
This is a bug that came from bad merge :)
Will include this fix in the next release.

Thanks

**Comment by gregswindle** [comment]
Thanks!
