### ISSUE TITLE
unable to register SVN package to PRIVATE_BOWER

### ISSUE THREAD

**Issue by mastermoin** [Hacklone/private-bower#150]
hi 
i am using visualSVN, and i have define one example module which has two files "readme.txt" & "bower,bowerrc"  now i want to register this package on private bower, 

so i am using command like 

bower register example-package svn+https://my-server.com:543/svn/example-module
bower register example-package svn+ssh://my-server.com:543/svn/example-module
bower register example-package svn+svn://my-server.com:543/svn/example-module

but all the time i got one similar error 

bower EINVFORMAT    The registry only accepts URLs starting with git://

can you please help me to come out with this problem 

private bower configuration "myBowerConfig.json" has entry link 

"svn": {
            "enabled": false,
            "cacheDirectory": "./svnRepoCache",
            "host": "https://my-sever.com",
            "port": 543,
            "publicAccessURL" : null,
            "refreshTimeout": 10
        }

**Comment by Hacklone** [comment]
Hey,

The error is provided by the bower client and not the private-bower server. Try adding the package through the private-bower webUI and then try to install it.
Hope this helps.

**Comment by mastermoin** [comment]
thanks i am able to add my package on private bower with webUI
