### ISSUE TITLE
unable to get package detail after click on package on web UI

### ISSUE THREAD

**Issue by mastermoin** [Hacklone/private-bower#153]
i am trying to create my fist bower package with one JS file 

alertThis.js

and than after i register it by "bower init". my bower.json file is looking like 

{
  "name": "example module",
  "version": "1",
  "description": "this is test module",
  "main": "alertThis.js",
  "keywords": [
    "alert",
    "this"
  ],
  "authors": [
    "moin"
  ],
  "license": "mit",
  "homepage": "mastermoin.com",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}

my packager registered successfully from web UI and  when i am trying to click on package name on web UI it is not retrieving package detail

**Comment by Hacklone** [comment]
This is a duplicate of #149
