### ISSUE TITLE
Unable to add package using rest API

### ISSUE THREAD

**Issue by vikasgithub** [Hacklone/private-bower#154]
We are using Private Bower version 1.0.1 and when I tried to register a package using rest API

bower-server:5678/packages/<package name> (I used my own corresponding server url)

I posted the URI in the body of the request in a format which was specified in the documentation.

I observed that the package got added to the bowerRepository.json, but the URI was missing. So, I had to manually update bowerRepository.json file to get that package registered.

Kindly let me know if this functionality works, otherwise I request you to provide a fix for this.

**Comment by Hacklone** [comment]
Hey,

Did you set the ```Content-Type``` header to ```application/json```?
