### ISSUE TITLE
Integration with private projects in Gitlab

### ISSUE THREAD

**Issue by Fost** [Hacklone/private-bower#158]
Hi!

How I can registery packages from private gitlab.domain.com ?
Project in gitlab is private.

I see message "Failed to load package details! (Your private-bower server needs read access to this Git repository!)"

Thanks!

**Comment by Hacklone** [comment]
Hey,

You'll have to grant access to your private-bower server to clone the repos :)

Hope this helps

**Comment by Fost** [comment]
Where in JSON config I should describe credentials?

**Comment by Hacklone** [comment]
You should use ssh to authenticate to your repo: http://doc.gitlab.com/ce/ssh/README.html
Configure your privatebower server to be able to clone your repos.

**Comment by Fost** [comment]
thanks, its done!

**Comment by Deshke** [comment]
ehm, little question, where should we configure this in the json config?

**Comment by Hacklone** [comment]
You cannot declare this in the config file. You'll have toconfigure your server to be able to use ssh for authenticating to your git repo.
For example configuring ssh for github: https://help.github.com/articles/generating-ssh-keys/

**Comment by Deshke** [comment]
got my workaround with the docker-compose if anyone runs in to this


```bash
bower-registry:
  image: tandrup/private-bower
  restart: always
  ports:
    - 5678:5678 
    - 6789:6789
    - 7891:7891
  environment:
    ADDRESS: <host>
  volumes:
    - /<persistent/path>:/data
    - /path/to/needed/ssh/credentials/.ssh:/root/.ssh/

```

**Comment by syjulian** [comment]
I am also getting the same error message when I use the UI. 

"Failed to load package details! (Your private-bower server needs read access to this Git repository!)"

I did the ssh authentication steps in github, and when I do "ssh -T git@github.com" it works, but I'm still getting errors

**Comment by fabdeceglia** [comment]
Hi guys,

i'm getting the message: 

`Failed to load package details! (Your private-bower server needs read access to this Git repository!)`

 on my private-bower setup trying connetct to my private gitlab repo.
This is the error spotted on the private-bower console (windows 7 powershell as admin):

`Error during "git clone git@kit-build02:FDC/fdc.custom.directives.git C:\Users\fdc\AppData\Roaming\npm\node_modules\private-bower\lib\temp\packageDetails\m5521tz753f03sor --depth=1" in "undefined". Output was: null`

If i launch the git clone command by myself it works without problems.

How to solve this?

**Comment by ionut-tanasa** [comment]
+1 on @fabdeceglia . it happens to me too

**Comment by ibhi** [comment]
+1

**Comment by pktito** [comment]
+1 on @fabdeceglia  , it happens to me too, like to @ionut-tanasa .

Please @Hacklone you can resolve that question ¿?

**Comment by cb3431** [comment]
Also having the same issue. I can run bower install from a command line on the server hosting private-bower and it works. 

Confirmed the ssh key is working.

**Comment by pekebuda** [comment]
+1
