### ISSUE TITLE
Is it possible to host the git repository cache on https:// or http://, rather than git://

### ISSUE THREAD

**Issue by nickhow83** [Hacklone/private-bower#161]
My current config contains the following section:

    "repositoryCache": {
            "cachePrivate": true,
            "git": {
                "enabled": true,
                "cacheDirectory": "./gitRepoCache",
                "host": "server-name",
                "port": 6789,
                "publicAccessURL" : null,
                "refreshTimeout": 100
            },

I was wondering if it would be possible to make the repository expose an endpoint such as https://server-name:6789

I'm currently working behind a proxy, so this is quite an important feature.

**Comment by Hacklone** [comment]
There could be an option, to save the mirrored package with a ```https://``` protocol.

**Comment by nickhow83** [comment]
What would be ideal is if it was possible to expose a https://server-name:6789 endpoint on the git repository cache.  As it stands, where I'm trying to set this up, there is a VPN trust between two domains, which go through a proxy, plus there's an external proxy (I know that this is the bigger issue, but that's outside of my control).  The result of this is that when I do a 'bower install' from the command-line, that it goes to git://server-name:6789, which it won't allow, even though this server is internal (as it still goes through a proxy, and therefore needs to use https).

Not sure if I've explained it very clearly, but it would be good to hear your thoughts on this.

Thanks

Nick

**Comment by Hacklone** [comment]
Hey,

What I understand is that you've enabled the git package mirroring, which by default creates a git repo with ```git://``` protocol registered but if there was an option that would force this new repo to be created with ```https://``` then you would be able to download these private repositories through you're proxy.

If I understood you correctly I'll do this in the next version :)

Thanks,
Barna

**Comment by nickhow83** [comment]
That's it exactly.  I'd be really happy if you could do that.  Thanks
