### ISSUE TITLE
Private-Bower does not recognize new version of package available

### ISSUE THREAD

**Issue by dhaval-vnc** [Hacklone/private-bower#163]
Hello private-bower team, 

I hosted your private bower. And registered some private repositories as well there. However when I try to install private packages using "bower install <package name>" it always fetches version 1.0.1 although we have version 1.0.1.3 (with proper tag) exists on the bower repo. 

Please help me out here if any special configuration required to tell private bower that the new version is available. 

Thank you, 
Dhaval.

**Comment by tarkabab** [comment]
http://semver.org/

**Comment by dhaval-vnc** [comment]
Got it thanks @tarkabab :)
