### ISSUE TITLE
Strange behaviour - anormal bowerRepositoryPublic.json

### ISSUE THREAD

**Issue by ludovicMercier** [Hacklone/private-bower#194]
Hi,

We had to restart our private bower server this morning and something strange happenned.
After the restart the file bowerRepositoryPublic.json has been updated and now is only 76ko with a strange content : [67,97,110,110,111,116,32,71,69,84,32,47,112,97,99,107,97,103,101,115,47,10]

Since this restart any research or intall worked.

Is there something wrong with the public repository ?

Thanks by advance

**Comment by ludovicMercier** [comment]
We have solved the problem by removing the **/** at the end of the repository configuration for bower.herokuapp like below : 

> **before**
> "registry": "http://bower.herokuapp.com/packages/,

> **after**
> "registry": "http://bower.herokuapp.com/packages",

**Comment by faisalferoz** [comment]
+1
