### ISSUE TITLE
Updated to 1.1.7 from 1.1.6 and lost all the packages

### ISSUE THREAD

**Issue by darkmavis1980** [Hacklone/private-bower#214]
Just updated the private-bower on my private bower server simply with `npm install -g private-bower`, rebooted the server, and now all the packages are gone :-|
Any idea?

**Comment by Hacklone** [comment]
Hey,

If you store the registry file within your private-bower instance (where npm installed it) npm will delete that folder when installing.

You can set the location of the registry file in the config file.

Hope you had backup :) 

Sorry,
Barna

**Comment by darkmavis1980** [comment]
I thought I did store it in a separate folder but at the end I didn't, my bad. Good thing we have backups
