### ISSUE TITLE
Error: write EIO

### ISSUE THREAD

**Issue by Toilal** [Hacklone/private-bower#223]
`private-bower` often stops with this error message.

```
[bower]  23/2/16 21:49:05   Exception message:Error: write EIO
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)
[bower]  23/2/16 21:49:05   Shutting down private-bower
```

Server is running on RedHat 6.

**Comment by Hacklone** [comment]
hope this helps: https://github.com/npm/npm/issues/3858
probably a problem with your hard drive or OS?

**Comment by Toilal** [comment]
Thanks. After moving the application to production server, it doesn't seem to occurs on it.
