### ISSUE TITLE
`invalid-meta` seen on registered bower package to private stash repo

### ISSUE THREAD

**Issue by erikyuzwa** [Hacklone/private-bower#224]
I'm very sorry to trouble anyone, from all accounts of reading the documentation my private bower package *should* be working correctly but it's not. 

Whenever I install my package with bower, it's found but I'm seeing `invalid-meta package-name is missing "ignore entry" in bower.json`

* I've semver tagged my bower package
* my bower.json contains an `ignore` entry which has the files/folders I want to ignore
* I've registered it to the private bower server using the url of our internal stash repo
* I've confirmed it's there via the private bower package webpage
* The private bower's config has our stash repo in the `repositoryCache` section

`bower info <package-name>` then returns the above mentioned `invalid-meta` message.

Any ideas?

**Comment by Hacklone** [comment]
Hey,
Could you send your bower.json?
Maybe it's invalid.

Thanks,
Barna

**Comment by erikyuzwa** [comment]
thanks @Hacklone - will do - apologies for the length

`{
  "name": "test-package",
  "description": "a test package for internal bower",
  "version": "0.0.4",
  "main": [
    "dist/js/test1.js",
    "dist/css/test1.css"
  ],
  "ignore": [
    "src",
    "test",
    "gulpfile.js",
    "karma-*.conf.js",
    "demo",
    "node_modules",
    "styles",
    ".bowerrc",
    ".gitattributes",
    ".gitignore",
    ".jshintrc",
    ".travis.yml",
    ".yo-rc.json",
    "bower"
  ],
  "devDependencies": {
    "angular": "^1.5.0",
    "lodash": "^4.2.1"
  }
}`

**Comment by Hacklone** [comment]
The bower.json seems fine, maybe the error is with your .bowerrc

**Comment by erikyuzwa** [comment]
thanks for confirming that at least @Hacklone. I'll go through the docs again on `.bowerrc`.

**Comment by erikyuzwa** [comment]
I can wrap this up. We were able to get this working :clap:

For future reference for others:
* make sure your `.bowerrc` contains a `"registry": "http://your-private-bower.com:5678"` entry
* if that doesn't help you out, then *uninstall* bower and re-install it. (note that I even tried a `bower cache clean` which didn't help. I needed the full uninstall).

thanks again @Hacklone
