### ISSUE TITLE
Examples of bowerRepositoryPublic.json and bowerRepository.json

### ISSUE THREAD

**Issue by sharikovvladislav** [Hacklone/private-bower#227]
Hi, Hacklone! Thank you for your project.

It is very helpfull and it would be great if I can adapt your project for my needs.

What I want to achieve?

- I want to host private registry, so I can store some private libs in it
- I want to proxy package requests to main bower registry, if there is no package in private registry

In your example config file you specify registryFile`s, but don't show examples of this files. Is it some kind of config files? Or is it just storage for some repositories?

**Comment by sharikovvladislav** [comment]
Update:

I just should wait some minutes :) After 2 minutes I got message about loading public repositories and got working proxy for public repositories.

Also, I noticed, that files json files were created automatically.

You can close this question ... =/

**Comment by Hacklone** [comment]
Hey,

Happy to hear that it works for you :)

Thanks,
Barna
