### ISSUE TITLE
proxy settings seem to not work

### ISSUE THREAD

**Issue by musikele** [Hacklone/private-bower#228]
Hi, I'm using private-bower behind a corporate proxy. ATM I have installed it on my machine and we plan to install it on our build server. 

these are my proxy settings: 

    "proxySettings" : {
        "enabled": true,
        "host": "http://localhost",
        "port": 9915,
        "tunnel": false
      },

I have tried even with tunnel : true. 

whe I start the server I get this: 
    private-bower --config ./bowerConfig.json

```
[bower]  18/4/16 11:13:58   Refreshing public packages...
[bower]  18/4/16 11:13:58   Cached public packages loaded
[bower]  18/4/16 11:13:58   private-bower server started
[bower]  18/4/16 11:13:58   something went wrong on the request
{ host: 'http://localhost',
  port: 9915,
  path: 'http://bower.herokuapp.com/packages',
  agent: false,
  method: 'GET',
  headers:
   { host: 'bower.herokuapp.com',
     'Content-Type': 'application/json',
     'Content-Length': 0 } }
```

and of course, when I do a basic `bower search angular` to test it out I get `No Results`. 

(If you are wondering why I have a proxy server on localhost, I have a little app that authenticates me on the real proxy server, this is used by many programs system wide (skype, firefox, intellij...) and I have no problems). 

How can I understand what's going on ?

**Comment by Hacklone** [comment]
Hey,

Did you try it with removing the ```http://``` from the host as protocol is not part of the host field.

Thanks,
Barna

**Comment by musikele** [comment]
thanks, it's working now. 
as a side note, it is working with "tunnel": true, and I think this depends on my configuration.
