### ISSUE TITLE
SVN package is not being downloaded 

### ISSUE THREAD

**Issue by musikele** [Hacklone/private-bower#229]
Hi, 
I am having some issues with private-bower and SVN. 
I have uploaded a package on SVN and I have created a <my-package>/tags/0.0.1/ directory that contains the version. 
I have created the package in private-bower by saying that the url is at <svn-url>/<my-package>/tags/ . 
(My svn server does not expose file structure via http). 

When I click on the project I see that private-bower is trying to access to the server via *git*. 

this is my config.json: 

```
{
  ...
  "repositoryCache": {
    "cachePrivate": false,
    "svn": {
      "enabled": false,
      "cacheDirectory": "./svnRepoCache",
      "host": "<my host without https>",
      "port": 443,
      "protocol": "https",
      "publicAccessURL" : null,
      "refreshTimeout": 10
    }
  },
 ...
}
```
Note that I have removed the "git" part since I don't use this protocol and I only want to use svn. 

any ideas of what I am doing wrong? 

```
[2016-04-19 10:34:35.884] [INFO] console - [bower]  19/4/16 10:34:35   Error during "git clone https://svnesel.eng.it/svn/areas/KPPHPDD/AreasJavascriptRepository/crypto-js/tag C:\Users\Michele\AppData\Roaming\npm\node_modules\private-bower\lib\temp\packageDetails\jbhvud2wabn019k9 --depth=1" in "undefined".
        Output:
                stdout:
                stderr: Cloning into 'C:\Users\Michele\AppData\Roaming\npm\node_modules\private-bower\lib\temp\packageDetails\jbhvud2wabn019k9'...
fatal: unable to access 'https://svnesel.eng.it/svn/areas/KPPHPDD/AreasJavascriptRepository/crypto-js/tag/': error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by Hacklone** [comment]
Hey,

SVN in private-bower is supported for svn urls containing ```svn+```. ie: ```svn+ssh://joe@compute.cs.columbia.edu/home/joe/repository/my_project``` 
I know this is a weakness but got no better idea how to differentiate between git and svn repos.

Thanks,
Barna

**Comment by musikele** [comment]
Ok, I just spoke with the sysadmin of my corporate network, it seems impossible for them to open the svn+https protocol. I'm going to switch to zip files (bower allows them). Now I have to understand how to version them ...
