### ISSUE TITLE
Team Foundation Server 2015

### ISSUE THREAD

**Issue by ViktorHofer** [Hacklone/private-bower#230]
Hi guys,

thanks for the great product! I'm keen using it in my company as a dedicated private bower repository. Currently we are storing our projects in Team Foundation Server 2015 Update 2. When connecting bower with TFS the details can't be fetched and bower install from the client is not working.

Is is mandatory to use Git SSH for security (key trust) or are there any other ways to connect both servers together? As TFS 2015 Update 3 will support Git SSH it's not that a big issue but I just wanted check on it.

So what do you think?

Thanks 👍

**Comment by Hacklone** [comment]
Hey,

You can use https too. Is there any issue with using that?

Barna

**Comment by ViktorHofer** [comment]
Hey,

I don't know how to tell private-bower how to get the git packages with authentication. Because the git Project is not available by public in corporate Team Foundation Server. Please see the Image below.

![private-bower-bug](https://cloud.githubusercontent.com/assets/7412651/14742696/d394c580-089d-11e6-8928-b1c7df2059a0.JPG)

**Comment by Hacklone** [comment]
Hey,

private-bower simply tries to clone the repo by calling ```git clone <you repo url>```.
So what's important is that you'll have to be able to clone the repo on the private-bower server.

For caching git repo credentials you can do that by using this on WIndows: https://github.com/Microsoft/Git-Credential-Manager-for-Windows

Or by using ssh :)

Hope this helps. :+1: 
Barna

**Comment by ViktorHofer** [comment]
Hi thanks for that!

I submitted a pull request for Fixing a little bug which hit me during package detail loading.
Now this works, but still need to investigate a bit further why package loading is not working.

Thanks so far!

**Comment by anwalkers** [comment]
@ViktorHofer I have run into this issue as well. This might be the answer if private bower had the ability configure the path to the SSH key. http://www.nodegit.org/guides/cloning/ssh-with-agent/ I a trying to host the private-bower server and site on a secured website in the cloud and call into repositories hosted in VSTS. I will attempt adding nodegit to my fork and call with an SSH key...
