### ISSUE TITLE
IE 11 frontend bug

### ISSUE THREAD

**Issue by ViktorHofer** [Hacklone/private-bower#231]
Currently the design of the frontend is broken in IE 11.

Thanks

**Comment by PatrickWalker** [comment]
![ie](https://cloud.githubusercontent.com/assets/1721689/20798031/4c163d36-b7d5-11e6-99ed-ecf1cc6132c9.png)
![edge](https://cloud.githubusercontent.com/assets/1721689/20798039/5153735e-b7d5-11e6-9ddb-514fdda0ef2f.png)

Shows the difference between ie11 and edge
