### ISSUE TITLE
private-bower as general git proxy

### ISSUE THREAD

**Issue by fjakop** [Hacklone/private-bower#236]
I've set up private-bower successfully and it works fine for bower install.

I wonder if it is possible to make this a store-and-forward proxy for any kind of git clone/fetch requests, so that even npm dependencies based on e.g. git+https could be cached.

In best case it would be a request like `git clone https://foo/repo.git` which is intercepted by private-bower, which clones the repo and rewrites the origin to `https://my.bower/repo`, so any followin interaction is handled through the private-bower server.

Would this be possible?

**Comment by Hacklone** [comment]
Hey,

private-bower does have a feature like that, it's called repositoryCache.
You can enable it in your config file:
```json
"repositoryCache": {
        "cachePrivate": false,  //This will enable caching private repositories - not sure you need this
        "git": {
            "enabled": true,  //This will enable chaching public git repositories
            "cacheDirectory": "./gitRepoCache",
            "host": "localhost",
            "port": 6789,
            "protocol": "git",
            "publicAccessURL" : null,
            "refreshTimeout": 10
        },
```

private-bower won't be able to cache npm packages as it's a bower repository not an npm repo :)

Hope this helped.

Barna

**Comment by fjakop** [comment]
Thanks for the answer. I'm aware that provate-bower does not cache npm packages, but my point is that I'd like to cache any git request (not only bower install) to the outside world with the repository cache of private-bower.

So if the git cache works as I expect, I just have to tell git that it should rewrite my request?

Or does private-bower cache *only* repos contained in the configured bower registry file?

**Comment by Hacklone** [comment]
Hey,

You can do that, by registering a package through the api or the webui.
Then simply clone the cloned git repo. :+1: 

Barna

**Comment by fjakop** [comment]
That's it, thx a lot!
