### ISSUE TITLE
Register package does not cache but only redirect

### ISSUE THREAD

**Issue by fjakop** [Hacklone/private-bower#240]
When I register a package which is not in the public bower registry but accessible via github, private-bower seems not to cache this repository but just redirects every access.

Example:
I register 'kotest' as 'https://github.com/arxes-tolina/kotest.git' via web UI, then I do `bower install --config.registry=http://my.private.bower/ kotest` and the hit counter increases, but no cache repo is created and my localhost accesses github directly.

Is this intended to behave like this? It would be very useful to have such artifacts also cached because of 
a) network load 
b) access time
c) no need to set a http-proxy for bower anymore

**Comment by Hacklone** [comment]
Hey,

This feature is called private package caching.
You can enable it in the config:
```json
"repositoryCache": {
        "cachePrivate": false, //Set this to true
```

**Comment by fjakop** [comment]
It works :+1: 
Thx
