### ISSUE TITLE
Could not load public packages, invalid data!

### ISSUE THREAD

**Issue by SrinivasanKuppuswamy** [Hacklone/private-bower#269]
[private-bower.txt](https://github.com/Hacklone/private-bower/files/1415200/private-bower.txt)
Hi all,
        When running private-bower from putty, I'm getting the below issue
"Could not load public packages, invalid data!"
 SyntaxError: Unexpected end of JSON input

Can anyone help me out to resolve this issue

**Comment by piermorosini** [comment]
Hi
private-bower runs as service with user www-data.
For serveral times I tried to memorize ssh credentials for this user.
But I failed.

**Comment by piermorosini** [comment]
Read here I think can help u
#268

**Comment by SrinivasanKuppuswamy** [comment]
This issue is resolved by updating the latest configuration codes in the private bower installation file
