### ISSUE TITLE
Certain packages are not resolving

### ISSUE THREAD

**Issue by maitriyogin** [Hacklone/private-bower#65]
Hi,
I have a few dependencies that maybe aren't standard, that don't resolve through private-bower but do when running directly against the public repo namely :
"matchmedia-ng": "~1.0.3",
"leaflet-china": "https://raw.github.com/htoooth/Leaflet.ChineseTmsProviders/master/src/leaflet.ChineseTmsProviders.js",
    
If I change ~ to "matchmedia-ng": "#1.0.3" it works!
Which is ok as a workaround but whats the problem with leaflet-china ?
Really looking forward to your reply,
/Stephen

**Comment by ludovicMercier** [comment]
Hi, 

I have the same problem with highlightjs  : 

 * Without private-bower : 

> $ bower install highlightjs
> bower highlightjs#*         not-cached https://github.com/components/highlightjs.git#*
> bower highlightjs#*            resolve https://github.com/components/highlightjs.git#*
> bower highlightjs#*           download https://github.com/components/highlightjs/archive/8.4.0.tar.gz
> bower highlightjs#*            extract archive.tar.gz
> bower highlightjs#*           resolved https://github.com/components/highlightjs.git#8.4.0
> bower highlightjs#~8.4.0       install highlightjs#8.4.0

* With private-bower : 

> bower highlightjs#~8                        ENOTFOUND Package highlightjs not found

**Comment by Hacklone** [comment]
Hey,

I don't think that bower should work with this kind of package declaration:
"leaflet-china": "direct file url"
but if it does then the problem could be with raw.github as it's intentionally doesn't serve with a right content type.
Try using: https://rawgit.com

I'm closing this as it looks like it's an issue with the bower client
