### ISSUE TITLE
Is it possible to add pathname to the config

### ISSUE THREAD

**Issue by mdiskin** [Hacklone/private-bower#66]
It's easier to put behind a reverse proxy (Apache httpd) when you have the same pathname.

**Comment by Hacklone** [comment]
Hey,

I still don't really get it. :)
private-bower needs a port for itself so this would be myServerDomainName:privateBowerPort/myCustomPath ?

You can sign multiple domain names to resolve to the same machine that way you can create a bower.myIntra.net:5678

**Comment by mdiskin** [comment]
It's for when want to proxy forward/reverse thru a common domain address where each path on that domain can be routed separately.

I did find this that might be something to look at for this and other use cases (e.g. Other paths deployed along side such as stats ,Api, ....)

https://www.npmjs.com/package/dynamic-reverse-proxy



Sent with Good (www.good.com)


-----Original Message-----

**Comment by royrico** [comment]
Hi,
Just want to add,t his feature would be **really** useful for corporate users.
