### ISSUE TITLE
Error message: Failed to clone (maybe folder exists)

### ISSUE THREAD

**Issue by niksy** [Hacklone/private-bower#85]
Every time I register and download some package for the first time, I get this error. For example, for jQuery:

```sh
[bower]  2/11/14 14:59:55  Failed to clone (maybe folder exists)git@github.com:jquery/jquery.git
[bower]  2/11/14 14:59:55  undefined
[bower]  2/11/14 15:00:28  Cloned jquery-test git repository to private
```

If I then clean Bower cache and try to download that same package, it will download from the private repository.

Am I doing something wrong?

**Comment by niksy** [comment]
Sorry for not being active on this issue :(

I’ve installed the latest version of private-bower but now I get this error:

```sh
[bower]  24/1/15 18:09:39   Loaded public packages
[bower]  24/1/15 18:10:27   Cloning jquery ...
[bower]  24/1/15 18:10:59   Cloning jquery ...
[bower]  24/1/15 18:10:59   Error during "git clone git://github.com/jquery/jquery.git jquery" in "/Users/niksy/Projects/private-bower/gitRepoCache"
[bower]  24/1/15 18:10:59   Error during cloning in jquery
[bower]  24/1/15 18:10:59   Command failed: fatal: destination path 'jquery' already exists and is not an empty directory.

[bower]  24/1/15 18:10:59   Registered package: jquery
```

And in directory where I’m trying to to install jQuery:

```sh
bower                            retry Request to http://localhost:5678/packages/jquery failed with ETIMEDOUT, retrying in 1.8s
bower jquery#*                 resolve git://localhost:6789/jquery#*
bower jquery#*            ENORESTARGET Tag/branch master does not exist

Additional error details:
No tags found in git://localhost:6789/jquery
No branches found in git://localhost:6789/jquery
```

Is this something related to this issue?

**Comment by Hacklone** [comment]
Try deleting the jQuery folder on your private-bower server and let it clone again. Though I'll fix the error, so that it checks if it's already there.

**Comment by Hacklone** [comment]
Can we close this issue? with version ```0.6.5``` ?

**Comment by andham** [comment]
I can't see any instructions in README.md on increasing the bower client timeout.

**Comment by Hacklone** [comment]
``` { "timeout": 120000 } ``` I'll add it to the README.md

**Comment by niksy** [comment]
Using different timeout value helped in cloning and install packages :)

But, I also encountered this error when cloning jQuery package:

```sh
bower jquery#*                  cached git://localhost:6789/jquery#2.1.3
bower jquery#*                validate 2.1.3 against git://localhost:6789/jquery#*
bower jquery#*                 ECMDERR Failed to execute "git ls-remote --tags --heads git://localhost:6789/jquery", exit code of #128

Additional error details:
fatal: remote error: access denied or repository not exported: /jquery
```
The only way I could resolve is via `--force` Bower install. Other packages like jQuery UI installed without problem.

**Comment by Hacklone** [comment]
```bower cache clean``` could also help. maybe something went wrong with your cloned jQuery

**Comment by niksy** [comment]
Yes, cache cleaning helped. I think this issue can be closed now :)
