### ISSUE TITLE
Private-bower goes down 

### ISSUE THREAD

**Issue by RameshMuthuraj** [Hacklone/private-bower#87]
Please check this log
root@ log]# tail -f private-bower.log
[bower]  10/11/14 8:50:20   Loaded public packages
[bower]  10/11/14 9:20:14   Loaded public packages
[bower]  10/11/14 9:50:14   Loaded public packages
[bower]  10/11/14 10:20:14   Loaded public packages
[bower]  10/11/14 10:50:14   Loaded public packages
[bower]  10/11/14 11:20:14   Loaded public packages
[bower]  10/11/14 11:50:14   Loaded public packages
[bower]  10/11/14 12:20:14   Loaded public packages
sudo: private-bower: command not found
sudo: sorry, you must have a tty to run sudo

Worklog 

created /etc/init/private-bower.conf file
description "private bower"
author "Ramesh Muthuraj"
start on started mountall
stop on shutdown
respawn
respawn limit 99 5
limit nofile 32768 32768
script
       cd /opt/bower
exec private-bower --config  ./myBowerConfig.json >> /var/log/private-bower.log 2>&1
end script

and this not running under redhat linux..and throws some error in log

**Comment by Hacklone** [comment]
Can I close this issue?
