### ISSUE TITLE
Can't register packages

### ISSUE THREAD

**Issue by Glenndejaeger** [Hacklone/private-bower#94]
Hi,

I'm unable to register packages to private-bower, probably because it's not clear for me if the git or svn url that should be passed as an argument should point to the repo containing the bower component you want to register or to a repo that's linked to private-bower itself.

In case the answer is the former, there's probably another issue.
Out project consists of 3 subprojects which are separate bower components and depend on each other via bower. However, they're source code is stored in the same SVN repo (but in a separate folder).
So if I should pass the svn repo url containing the bower component I want to store in private-bower, I should pass 3x the same url but a different bower component name. Can this work?

**Comment by Hacklone** [comment]
Could you check the bowerRegistry.json file on your server? You should see something like this:
```[ { "name": "myPackageName", "repo": "myGithubUrl" } ]```

**Comment by Hacklone** [comment]
Closing this ticket for inactivity
