### ISSUE TITLE
hi newbie here..setup a private bower for internal use

### ISSUE THREAD

**Issue by rudhuwan** [Hacklone/private-bower#96]
I have installed private-bower and got a webpage up (http://x.x.x.x.:5678)
I have created a sample project with yeoman. From README, it said I have to insert
{ "registry": "http://x.x.x.x:5678" } into my .bowerrc. So I did that.

Being a newbie, how should I test to see if the dependencies downloaded through the private bower that I have setup.
I start my private bower with the default config file.

Any kind of response is highly appreciated.

duan

**Comment by Hacklone** [comment]
Hey sorry for being late with the answer :) Register a private package ```bower register myPrivateTestPackage git://fake.git``` then put the .bowerrc in a folder. In that folder run ```bower install myPrivateTestPackage``` bower will have to log out ```git://fake.git is not found``` but that means that the git url came from your private-bower registry :)

Hope this helps.

**Comment by Hacklone** [comment]
Closing this ticket for inactivity
